### ISSUE TITLE
Typo in the project info

### ISSUE THREAD

**Issue by ccoVeille** [raeperd/kickstart.go#23]
![Screenshot_20241208_120723_GitHub.jpg](https://github.com/user-attachments/assets/0939fa4f-e0e3-47c1-9d03-0baab762392b)

I assume it's server, not server

But then I would recommend fixing HTTP and Go, respectively an acronym and a brand.

So it would end like this

Minimalistic **HTTP** serv**er** template in **Go**

I cannot open a PR for this

**Comment by raeperd** [comment]
Thanks for report! I fixed it right away
